# Generated by Django 5.1.4 on 2025-01-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='user_uu',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
