# Generated by Django 5.1.4 on 2025-01-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userextra_user_uu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='location',
        ),
        migrations.AddField(
            model_name='userextra',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userextra',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
