# Generated by Django 5.1.4 on 2025-01-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userextra_city_userextra_email_userextra_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextra',
            old_name='name',
            new_name='Last_name',
        ),
        migrations.AddField(
            model_name='userextra',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
