# Generated by Django 5.1.4 on 2025-01-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_name_userextra_last_name_userextra_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='userextra',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userextra',
            name='first_name',
        ),
    ]
