# Generated by Django 5.1.3 on 2025-01-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orders_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='price',
            new_name='amount',
        ),
    ]
