# Generated by Django 5.1.4 on 2025-01-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_price_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_capture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
