# Generated by Django 5.1.4 on 2025-01-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orders_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
