# Generated by Django 5.1.4 on 2025-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_orders_options_orders_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
