# Generated by Django 5.1.4 on 2025-01-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='razor_pay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='razor_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='razor_payment_signature',
            new_name='razorpay_signature',
        ),
    ]
