# Generated by Django 5.1.4 on 2025-01-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_razor_pay_order_id_orders_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.JSONField(default=dict),
        ),
    ]
