# Generated by Django 5.1.4 on 2025-01-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_orders_items_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
